version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps):"
    groups:
      go-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
